# Generated by Django 2.2 on 2022-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
